import java.awt.Color;
import java.util.prefs.Preferences;

public class EndScreen extends javax.swing.JFrame {

    Preferences prefs = Preferences.userNodeForPackage(getClass());
    Minesweeper2 gameWindow;

    public EndScreen(boolean win, Minesweeper2 gameWindow) {
        initComponents();

        this.gameWindow = gameWindow;

        setLocationRelativeTo(null);

        int games = prefs.getInt("games", 0);
        int wins = prefs.getInt("wins", 0);
        int highScore = prefs.getInt("highScore", 0);
        boolean insane = prefs.getBoolean("insane", false);

        xText.setText("" + prefs.getInt("x", 16));
        yText.setText("" + prefs.getInt("y", 16));
        minesText.setText("" + prefs.getInt("mines", 52));
        tileSizeText.setText("" + prefs.getInt("tileSize", 28));
        colorText.setText(prefs.get("color", "#008000"));
        botCheck.setSelected(prefs.getBoolean("bot", false));
        getContentPane().setBackground(Color.decode(colorText.getText()));

        games++;
        if (!win) {
            endMessage.setText("Sorry, you lose!");
        } else {
            wins++;
        }

        if (gameWindow.gameTime >= 10) {
            progress.setValue(gameWindow.progress);

            int gameTimeH = gameWindow.gameTime / 3600;
            int gameTimeM = gameWindow.mod(gameWindow.gameTime, 3600) / 60;
            int gameTimeS = gameWindow.mod(gameWindow.gameTime, 60);
            gameTime.setText(" " + gameTimeH + ":" + gameTimeM + ":" + gameTimeS);

            int mineRatio = gameWindow.xTiles * gameWindow.yTiles / gameWindow.mineCount;
            mineRatioText.setText(" " + mineRatio);

            if (gameWindow.xTiles * gameWindow.yTiles < 2448) {
                double score = ((double) gameWindow.progress * 10000 / (double) mineRatio) / ((double) gameWindow.gameTime - ((double) gameWindow.gameTime * (((double) gameWindow.xTiles * (double) gameWindow.yTiles) / 2448)));
                if (gameWindow.xTiles >= 10 && gameWindow.yTiles >= 10 && (double) gameWindow.mineCount / (gameWindow.xTiles * gameWindow.yTiles) >= 0.15) {
                    scoreText.setText(" " + (int) score);
                    if (score > highScore) {
                        highScore = (int) score;
                    }
                } else {
                    scoreText.setText(" N/a");
                }
            } else if (mineRatio <= 4) {
                scoreText.setText(" Insane!");
                prefs.putBoolean("insane", true);
            }
        } else {
            gameTime.setText(" N/a");
            mineRatioText.setText(" N/a");
            scoreText.setText(" N/a");
        }

        gamesPlayed.setText(" " + games);
        winsText.setText(" " + wins);
        lost.setText(" " + (games - wins));
        if (games > 0) {
            double percentage = (double) wins / games * 100;
            percentageText.setText(" " + (int) percentage + " %");
        }
        if (!insane) {
            highScoreText.setText(" " + highScore);
        } else {
            highScoreText.setText(" Insane!");
        }

        prefs.putInt("games", games);
        prefs.putInt("wins", wins);
        prefs.putInt("highScore", highScore);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        yText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minesText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tileSizeText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        colorText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        gameTime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mineRatioText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scoreText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        gamesPlayed = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        winsText = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lost = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        percentageText = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        highScoreText = new javax.swing.JLabel();
        returnMenu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        playAgain = new javax.swing.JButton();
        endMessage = new javax.swing.JLabel();
        botCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText(" Horizontal ");
        jPanel2.add(jLabel1);

        xText.setText(" 16");
        jPanel2.add(xText);

        jLabel8.setText(" Vertical");
        jPanel2.add(jLabel8);

        yText.setText(" 16");
        jPanel2.add(yText);

        jLabel3.setText(" Mines");
        jPanel2.add(jLabel3);

        minesText.setText(" 52");
        jPanel2.add(minesText);

        jLabel4.setText(" Tile size");
        jPanel2.add(jLabel4);

        tileSizeText.setText(" 28");
        jPanel2.add(tileSizeText);

        jLabel5.setText(" Color-RGB");
        jPanel2.add(jLabel5);

        colorText.setText(" #008000");
        jPanel2.add(colorText);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setText(" Progress");
        jPanel3.add(jLabel2);

        progress.setBackground(new java.awt.Color(255, 255, 255));
        progress.setPreferredSize(new java.awt.Dimension(50, 12));
        jPanel3.add(progress);

        jLabel6.setText(" Time");
        jPanel3.add(jLabel6);

        gameTime.setText(" gameTime");
        jPanel3.add(gameTime);

        jLabel7.setText(" Tiles/Mines");
        jPanel3.add(jLabel7);

        mineRatioText.setText(" mineRatioText");
        jPanel3.add(mineRatioText);

        jLabel9.setText(" Total Score");
        jPanel3.add(jLabel9);

        scoreText.setText(" scoreText");
        jPanel3.add(scoreText);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(new java.awt.GridLayout(5, 2));

        jLabel15.setText(" Total Games played");
        jPanel4.add(jLabel15);

        gamesPlayed.setText(" 0");
        jPanel4.add(gamesPlayed);

        jLabel11.setText(" Games Won");
        jPanel4.add(jLabel11);

        winsText.setText(" 0");
        jPanel4.add(winsText);

        jLabel13.setText(" Games Lost");
        jPanel4.add(jLabel13);

        lost.setText(" 0");
        jPanel4.add(lost);

        jLabel16.setText(" Win percentage");
        jPanel4.add(jLabel16);

        percentageText.setText(" 0 %");
        jPanel4.add(percentageText);

        jLabel18.setText(" High Score");
        jPanel4.add(jLabel18);

        highScoreText.setText(" 0");
        jPanel4.add(highScoreText);

        returnMenu.setText("Return to Menu");
        returnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMenuActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        playAgain.setText("Play again");
        playAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainActionPerformed(evt);
            }
        });

        endMessage.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        endMessage.setText("Congratulations, you win!");

        botCheck.setText("Bot");
        botCheck.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnMenu)
                    .addComponent(botCheck))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playAgain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(endMessage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(endMessage)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(botCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnMenu)
                    .addComponent(exit)
                    .addComponent(playAgain))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void returnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuActionPerformed
        gameWindow.dispose();
        new Menu2();
        dispose();
    }//GEN-LAST:event_returnMenuActionPerformed

    private void playAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainActionPerformed
        gameWindow.dispose();
        new Minesweeper2(Integer.parseInt(xText.getText()), Integer.parseInt(yText.getText()), Integer.parseInt(minesText.getText()), Color.decode(colorText.getText()), Integer.parseInt(tileSizeText.getText()), botCheck.isSelected());
        dispose();

    }//GEN-LAST:event_playAgainActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox botCheck;
    private javax.swing.JLabel colorText;
    private javax.swing.JLabel endMessage;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gameTime;
    private javax.swing.JLabel gamesPlayed;
    private javax.swing.JLabel highScoreText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lost;
    private javax.swing.JLabel mineRatioText;
    private javax.swing.JLabel minesText;
    private javax.swing.JLabel percentageText;
    private javax.swing.JButton playAgain;
    private javax.swing.JProgressBar progress;
    private javax.swing.JButton returnMenu;
    private javax.swing.JLabel scoreText;
    private javax.swing.JLabel tileSizeText;
    private javax.swing.JLabel winsText;
    private javax.swing.JLabel xText;
    private javax.swing.JLabel yText;
    // End of variables declaration//GEN-END:variables
}
